### ISSUE TITLE
🏁 Breach & Clean ↔ v18.5.0

### ISSUE THREAD

**Issue by senaayazberat** [itchio/itch-compatibility-watchlist#62] opened 2016-08-06 14:06 UTC
:rotating_light: game [Breach & Clean](https://ramiismail.itch.io/breach-and-clean) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/6fe72ad891bafffd7c207c617dae27b9).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2016-08-07 06:34
Duplicate of #61

**Closed as completed by fasterthanlime** 2016-08-07 06:34 UTC
