### ISSUE TITLE
🏁 Breach & Clean ↔ v18.6.2

### ISSUE THREAD

**Issue by Emreqwsa** [itchio/itch-compatibility-watchlist#114] opened 2016-08-28 14:29 UTC
:rotating_light: game [Breach & Clean](https://ramiismail.itch.io/breach-and-clean) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/5bbac909eedaaa426a854ddaf36f9a4c).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2016-08-29 08:46
duplicate of #111

**Closed as completed by fasterthanlime** 2016-08-29 08:46 UTC
