### ISSUE TITLE
🏁 My Little Blacksmith Shop ↔ v23.4.1

### ISSUE THREAD

**Issue by joshboy907** [itchio/itch-compatibility-watchlist#1035] opened 2017-07-07 21:25 UTC
:rotating_light: game [My Little Blacksmith Shop](https://dasius.itch.io/my-little-blacksmith-shop) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/88039cecb0cf53a1905e3c63a58acfec).

:running: Any additional details can go here!

**Comment by joshboy907** [comment] 2017-07-07 21:25
I need help to fix this

**Comment by fasterthanlime** [comment] 2017-07-07 22:11
Duplicate of #1033

**Closed as completed by fasterthanlime** 2017-07-07 22:11 UTC
