### ISSUE TITLE
🍎 Tube Tycoon ↔ v23.4.2

### ISSUE THREAD

**Issue by GalacticJames** [itchio/itch-compatibility-watchlist#1070] opened 2017-07-17 17:20 UTC
:rotating_light: game [Tube Tycoon](https://bionicl.itch.io/tubetycoon) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/a5cfe0d752205450e270b318b98de0fc).

:running: Any additional details can go here! It's not starting up for me

**Comment by fasterthanlime** [comment] 2017-07-17 18:00
Duplicate of #1068

**Closed as completed by fasterthanlime** 2017-07-17 18:00 UTC
