### ISSUE TITLE
🏁 Struggle Offensive ↔ v23.4.2

### ISSUE THREAD

**Issue by l0gik6l-jynx** [itchio/itch-compatibility-watchlist#1145] opened 2017-09-02 01:02 UTC
:rotating_light: game [Struggle Offensive](https://rakarnov.itch.io/struggle-offensive) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/58c89ebc44fac4e222218bf8ef9cb9b5).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2017-09-02 01:08
I've reached out to the developers, hoping they make their game compatible with the itch app soon.

Duplicate of #1142

**Closed as completed by fasterthanlime** 2017-09-02 01:08 UTC
