### ISSUE TITLE
🏁 Raft ↔ v23.0.0

### ISSUE THREAD

**Issue by mh2311** [itchio/itch-compatibility-watchlist#606] opened 2017-01-23 10:49 UTC
:rotating_light: game [Raft](https://raft.itch.io/raft) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/2870eb3fd0d146bd7d0315919c66d23e).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2017-02-01 13:11
Duplicate of #605

**Closed as completed by fasterthanlime** 2017-02-01 13:11 UTC
