### ISSUE TITLE
🏁 Breach & Clean ↔ v19.0.0

### ISSUE THREAD

**Issue by Frabs69** [itchio/itch-compatibility-watchlist#288] opened 2016-11-19 21:04 UTC
:rotating_light: game [Breach & Clean](https://ramiismail.itch.io/breach-and-clean) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/c3ba9f146222f732030e2ee72f2ef87b).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2016-11-19 22:36
Duplicate of #287

**Closed as completed by fasterthanlime** 2016-11-19 22:36 UTC
