### ISSUE TITLE
🍎 Tube Tycoon ↔ v23.3.1

### ISSUE THREAD

**Issue by littlepeppermaze** [itchio/itch-compatibility-watchlist#839] opened 2017-03-25 05:49 UTC
:rotating_light: game [Tube Tycoon](https://bionicl.itch.io/tubetycoon) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/cda20ec96b7bc98eae2c4f06300b95dd).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2017-03-25 09:11
Duplicate of #840

**Closed as completed by fasterthanlime** 2017-03-25 09:11 UTC
