### ISSUE TITLE
🏁 Raft ↔ v23.0.0

### ISSUE THREAD

**Issue by yuvaly1** [itchio/itch-compatibility-watchlist#580] opened 2017-01-19 18:56 UTC
:rotating_light: game [Raft](https://raft.itch.io/raft) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/3c5b3b408590a88e53ebcd92d709a9b6).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2017-02-01 13:11
Duplicate of #579

**Closed as completed by fasterthanlime** 2017-02-01 13:11 UTC
