### ISSUE TITLE
🍎 Tube Tycoon ↔ v18.6.1

### ISSUE THREAD

**Issue by smartin723** [itchio/itch-compatibility-watchlist#101] opened 2016-08-25 04:46 UTC
:rotating_light: game [Tube Tycoon](https://bionicl.itch.io/tubetycoon) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/17f0387bda28d54cf713249a2958ed0c).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2016-08-25 07:51
duplicate of #100

**Closed as completed by fasterthanlime** 2016-08-25 07:51 UTC
