### ISSUE TITLE
please chyba please

### ISSUE THREAD

**Issue by fronar** [itchio/itch-compatibility-watchlist#433] opened 2016-12-15 18:01 UTC
:rotating_light: game [The Pedestrian](https://the-pedestrian.itch.io/the-pedestrian) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/2e1d7bed1042eab4844a896ce54075c5).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2016-12-15 20:35
duplicate of #434

**Closed as completed by fasterthanlime** 2016-12-15 20:35 UTC
