### ISSUE TITLE
🍎 Tube Tycoon ↔ v23.4.2

### ISSUE THREAD

**Issue by GalacticJames** [itchio/itch-compatibility-watchlist#1069] opened 2017-07-17 17:01 UTC
:rotating_light: game [Tube Tycoon](https://bionicl.itch.io/tubetycoon) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/3ea400826544c34d92b29631af463d5e).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2017-07-17 18:00
Duplicate of #1068

**Closed as completed by fasterthanlime** 2017-07-17 18:00 UTC
