### ISSUE TITLE
🍎 Tube Tycoon ↔ v23.4.2

### ISSUE THREAD

**Issue by GalacticJames** [itchio/itch-compatibility-watchlist#1074] opened 2017-07-18 22:50 UTC
:rotating_light: game [Tube Tycoon](https://bionicl.itch.io/tubetycoon) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/d74ca4926e8c13908d225461d0f57a8f).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2017-07-24 10:17
Duplicate of #1062 - no known fix at the moment, and I'm not able to reproduce the issue :(

**Closed as completed by fasterthanlime** 2017-07-24 10:17 UTC
