### ISSUE TITLE
🏁 Ravenfield (Beta 4) ↔ v18.10.1

### ISSUE THREAD

**Issue by Winseven4lyf** [itchio/itch-compatibility-watchlist#223] opened 2016-10-29 01:21 UTC
:rotating_light: game [Ravenfield (Beta 4)](https://steelraven7.itch.io/ravenfield) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/49b431fe80e9a82b3a41bbc89fc677ef).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2016-10-29 09:02
Duplicate of #222

**Closed as completed by fasterthanlime** 2016-10-29 09:02 UTC
