### ISSUE TITLE
🏁 Wetwork ↔ v23.2.1

### ISSUE THREAD

**Issue by joloplayer** [itchio/itch-compatibility-watchlist#735] opened 2017-02-25 16:21 UTC
:rotating_light: game [Wetwork](https://serioussam909.itch.io/wetwork) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/15b9e564c5dd227515644e17392b1725).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2017-02-25 17:21
Duplicate of #734

**Closed as completed by fasterthanlime** 2017-02-25 17:21 UTC
