### ISSUE TITLE
🏁 Raft ↔ v22.2.0

### ISSUE THREAD

**Issue by Finngg1234** [itchio/itch-compatibility-watchlist#468] opened 2016-12-24 04:20 UTC
:rotating_light: game [Raft](https://raft.itch.io/raft) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/43fb8b85c13581742eaad54fae7e9054).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2016-12-24 17:38
Duplicate of #467

**Closed as completed by fasterthanlime** 2016-12-24 17:38 UTC
