### ISSUE TITLE
🏁 Monster Girl Island ↔ v23.4.1

### ISSUE THREAD

**Issue by SavageMoon** [itchio/itch-compatibility-watchlist#968] opened 2017-06-01 00:49 UTC
:rotating_light: game [Monster Girl Island](https://redamz.itch.io/monstergirlisland) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/3a7791d9094892457618644530e630e0).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2017-06-01 10:54
Duplicate of #966

**Closed as completed by fasterthanlime** 2017-06-01 10:54 UTC
