### ISSUE TITLE
🏁 Breach & Clean ↔ v18.7.0

### ISSUE THREAD

**Issue by luki22** [itchio/itch-compatibility-watchlist#142] opened 2016-09-08 16:15 UTC
:rotating_light: game [Breach & Clean](https://ramiismail.itch.io/breach-and-clean) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/c92ec0ce0006b571aff498ae05eeb054).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2016-09-08 17:50
duplicate of #140

**Closed as completed by fasterthanlime** 2016-09-08 17:50 UTC
