### ISSUE TITLE
🏁 Breach & Clean ↔ v18.6.2

### ISSUE THREAD

**Issue by Emreqwsa** [itchio/itch-compatibility-watchlist#112] opened 2016-08-28 14:27 UTC
:rotating_light: game [Breach & Clean](https://ramiismail.itch.io/breach-and-clean) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/919e5237d46cb6a40d2334c9cc745a0f).

:running: Any additional details can go here!

**Comment by Emreqwsa** [comment] 2016-08-28 14:28
Super

**Comment by Emreqwsa** [comment] 2016-08-28 14:28
Subsrribe

**Comment by fasterthanlime** [comment] 2016-08-29 08:46
duplicate of #111

**Closed as completed by fasterthanlime** 2016-08-29 08:46 UTC
