### ISSUE TITLE
🏁 Monster Girl Island ↔ v23.4.1

### ISSUE THREAD

**Issue by SavageMoon** [itchio/itch-compatibility-watchlist#967] opened 2017-05-31 23:19 UTC
:rotating_light: game [Monster Girl Island](https://redamz.itch.io/monstergirlisland) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/f9993abef82ed0c02a91a9c1f2cf20b3).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2017-06-01 10:54
Duplicate of #966

**Closed as completed by fasterthanlime** 2017-06-01 10:54 UTC
