### ISSUE TITLE
🏁 Winds of Revenge ↔ v19.0.0

### ISSUE THREAD

**Issue by Frxn69** [itchio/itch-compatibility-watchlist#296] opened 2016-11-20 15:23 UTC
:rotating_light: game [Winds of Revenge](https://allshar.itch.io/winds-of-revenge) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/9143a824135923b9d71b4ca824045b1a).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2016-11-20 16:25
Duplicate of #295

**Closed as completed by fasterthanlime** 2016-11-20 16:25 UTC
