### ISSUE TITLE
🐧 Sagittarius ↔ v19.0.0

### ISSUE THREAD

**Issue by ls-1N** [itchio/itch-compatibility-watchlist#236] opened 2016-11-05 13:40 UTC
:rotating_light: game [Sagittarius](https://gprosser.itch.io/sagittarius) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/b74cf8dc83b9774115e6aea54c058fe1).

:running: Xubuntu 14.04

EDIT: How do i delete this? Apparently there is an issue just like mine already.

**Comment by fasterthanlime** [comment] 2016-11-05 14:04
> EDIT: How do i delete this? Apparently there is an issue just like mine already.

You don't :) you just close it.

Closing as duplicate of #235

**Closed as completed by fasterthanlime** 2016-11-05 14:04 UTC
