### ISSUE TITLE
🐧 Pixel Proof ↔ v23.4.2

### ISSUE THREAD

**Issue by luziuu97** [itchio/itch-compatibility-watchlist#1127] opened 2017-08-20 22:05 UTC
:rotating_light: tool [Pixel Proof](https://dinomage.itch.io/pixel-proof) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/d21e03d3970021304c1f55d7cf6d686e).

:running: Any additional details can go here!

Had to manually install libsdl on Ubuntu 16.04 for PixelProof to work.

**Comment by fasterthanlime** [comment] 2017-08-21 00:23
Duplicate of #1128

**Closed as completed by fasterthanlime** 2017-08-21 00:23 UTC
