### ISSUE TITLE
🍎 Tube Tycoon ↔ v23.3.1

### ISSUE THREAD

**Issue by littlepeppermaze** [itchio/itch-compatibility-watchlist#841] opened 2017-03-25 06:03 UTC
:rotating_light: game [Tube Tycoon](https://bionicl.itch.io/tubetycoon) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/a4ead5865e5fb2df0bd85e0d35d04372).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2017-03-25 09:11
Duplicate of #840

**Closed as completed by fasterthanlime** 2017-03-25 09:11 UTC
