### ISSUE TITLE
🏁 Aven Colony (Beta) ↔ v18.10.0

### ISSUE THREAD

**Issue by YoannMa** [itchio/itch-compatibility-watchlist#174] opened 2016-09-20 19:31 UTC
:rotating_light: game [Aven Colony (Beta)](https://mothership.itch.io/aven-colony) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/c8f82883cf8cf01acbed8184de693e1b).

:running: Any additional details can go here!

It was working before the launcher update

**Comment by fasterthanlime** [comment] 2016-09-20 20:33
Duplicate of #173

**Closed as completed by fasterthanlime** 2016-09-20 20:33 UTC
