### ISSUE TITLE
🏁 Tanks of Freedom ↔ v18.6.2

### ISSUE THREAD

**Issue by harlamGrepper** [itchio/itch-compatibility-watchlist#135] opened 2016-09-07 08:57 UTC
:rotating_light: game [Tanks of Freedom](https://w84death.itch.io/tanks-of-freedom) is broken for me.

:book: Here's the complete [debug log](https://gist.github.com/f2d179235c1ba1d769293412826b51fa).

:running: Any additional details can go here!

**Comment by fasterthanlime** [comment] 2016-09-07 10:58
Duplicate of #134

**Closed as completed by fasterthanlime** 2016-09-07 10:58 UTC
